set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports {KEY[2]}]

set_property PACKAGE_PIN P17 [get_ports CLK]
set_property PACKAGE_PIN V12 [get_ports cs]
set_property PACKAGE_PIN U12 [get_ports miso]
set_property PACKAGE_PIN V11 [get_ports mosi]
set_property PACKAGE_PIN V10 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports output_flag]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]

set_property PACKAGE_PIN B11 [get_ports {seg[0]}]
set_property PACKAGE_PIN F14 [get_ports {seg[3]}]
set_property PACKAGE_PIN D13 [get_ports {seg[5]}]
set_property PACKAGE_PIN F13 [get_ports {seg[2]}]
set_property PACKAGE_PIN D15 [get_ports {seg[6]}]
set_property PACKAGE_PIN C15 [get_ports {seg[7]}]
set_property PACKAGE_PIN A11 [get_ports {seg[1]}]
set_property PACKAGE_PIN D12 [get_ports {seg[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN D14 [get_ports {sel[0]}]
set_property PACKAGE_PIN C14 [get_ports {sel[1]}]
set_property PACKAGE_PIN A10 [get_ports {sel[2]}]
set_property PACKAGE_PIN A9 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {KEY[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {KEY[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {KEY[0]}]


set_property PACKAGE_PIN U7 [get_ports SCK_I2C]
set_property IOSTANDARD LVCMOS33 [get_ports SCK_I2C]
set_property PACKAGE_PIN T8 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports sda]

set_property PACKAGE_PIN D10 [get_ports flag_I2C]
set_property IOSTANDARD LVCMOS33 [get_ports flag_I2C]

set_property PACKAGE_PIN D9 [get_ports LED_2]
set_property IOSTANDARD LVCMOS33 [get_ports LED_2]
